### ISSUE TITLE
Some random brainfarts / suggestions. 

### ISSUE THREAD

**Issue by bobdenotter** [DennisSnijder/BoltThemeOptions#5]
Hi Dennis, some suggestions for your extension. It looks really promising. :-)

 - The `<input>` fields look a bit out of place. Perhaps this is better if you add a `class='form-control'` to them. 
 - Repeat the 'save' button at the bottom too. 
 - Add a more complete example to README. 

And I like Zomars' suggestion too: If you can have it read / write `theme.yml` that'd be amazeballs. :-)

**Comment by zomars** [comment]
Bumping this!

**Comment by DennisSnijder** [comment]
Thanks for the suggestions @bobdenotter 👍
Will look into implementing the suggestions :)

**Comment by DennisSnijder** [comment]
I created another issue for the 'theme.yml' part
#6
